SELECT
    CAST(l_orderkey      AS INTEGER)   AS orderkey,
    CAST(l_partkey       AS INTEGER)   AS partkey,
    CAST(l_suppkey       AS INTEGER)   AS suppkey,
    CAST(l_linenumber    AS INTEGER)   AS linenumber,
    CAST(l_quantity      AS INTEGER)   AS quantity,
    CAST(l_extendedprice AS NUMERIC)   AS extendedprice,
    CAST(l_discount      AS NUMERIC)   AS discount,
    CAST(l_tax           AS NUMERIC)   AS tax,
    CAST(l_returnflag    AS TEXT)      AS returnflag,
    CAST(l_linestatus    AS TEXT)      AS linestatus,
    CAST(l_shipdate      AS DATE)      AS shipdate,
    CAST(l_commitdate    AS DATE)      AS commitdate,
    CAST(l_receiptdate   AS DATE)      AS receiptdate,
    CAST(l_shipinstruct  AS TEXT)      AS shipinstruct,
    CAST(l_shipmode      AS TEXT)      AS shipmode,
    CAST(l_comment       AS TEXT)      AS comment,
    CAST(created_at      AS TIMESTAMP) AS created_at
FROM {{ source('tpch', 'lineitem_tpch') }}